// Cert Tracker — generic role-aware career decision interface.
// Personal career data should remain outside the public repository.
(function initCareerUI(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.careerFramework||!CT?.recommendations)return;const esc=CT.util.escapeHtml;
  function injectStyle(){if(document.getElementById('ct-career-style'))return;const s=document.createElement('style');s.id='ct-career-style';s.textContent=`#ct-career-launcher{position:fixed;left:92px;bottom:18px;z-index:9997;border:1px solid rgba(255,255,255,.18);background:rgba(23,17,48,.94);color:#fff;border-radius:999px;padding:10px 14px;font:600 12px/1 ui-sans-serif,system-ui,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.32);cursor:pointer;backdrop-filter:blur(14px)}.ct-career-score{display:grid;grid-template-columns:repeat(6,minmax(48px,1fr));gap:6px;margin-top:8px}.ct-career-score>span{border:1px solid rgba(255,255,255,.09);border-radius:8px;padding:7px 4px;text-align:center;font:700 11px ui-monospace,monospace}.ct-career-score small{display:block;margin-top:3px;color:#aaa4c8;font:500 9px ui-sans-serif,system-ui,sans-serif}.ct-career-selects{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ct-career-selects label{font-size:10px;color:#aaa4c8}.ct-career-selects select{width:100%;margin-top:4px;background:#0f0b22;border:1px solid rgba(255,255,255,.14);color:#fff;border-radius:8px;padding:8px;font:600 11px ui-sans-serif,system-ui,sans-serif}@media(max-width:640px){#ct-career-launcher{left:82px;bottom:12px}.ct-career-selects{grid-template-columns:1fr}.ct-career-score{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(s);}
  function roleOptions(selected){return Object.entries(CT.careerFramework.ROLE_PROFILES).map(([key,p])=>`<option value="${esc(key)}"${key===selected?' selected':''}>${esc(p.label)}</option>`).join('');}
  function scoreHtml(card){return `<div class="ct-career-score"><span>M${card.M}<small>MARKET</small></span><span>K${card.K}<small>KNOWLEDGE</small></span><span>C${card.C}<small>CURRENT</small></span><span>N${card.N}<small>NEXT</small></span><span>E${card.E}<small>ENDGAME</small></span><span>${esc(card.T)}<small>TIMING</small></span></div>`;}
  function row(item){return `<div class="ct3-row"><div style="flex:1"><strong>${esc(item.name)}</strong><div class="ct3-muted">${esc((item.reasons||[]).slice(0,2).join(' · '))}</div>${scoreHtml(item.career)}</div><div style="text-align:right"><strong>${esc(item.marketValue?.contributionLabel||'n/a')}</strong><div class="ct3-muted">opportunity signal</div></div></div>`;}
  function close(root){root?.remove();}
  function open(){const existing=document.getElementById('ct-career-modal');if(existing){existing.remove();return;}const ctx=CT.careerFramework.context();const picks=CT.recommendations.recommendationsByHorizon({limit:3});const root=document.createElement('div');root.id='ct-career-modal';root.className='ct3-backdrop';root.innerHTML=`<section class="ct3-panel" role="dialog" aria-modal="true" aria-label="Career decision model"><div class="ct3-head"><div><div class="ct3-title">Career decision model</div><div class="ct3-sub">Separate market value, practical knowledge and role relevance</div></div><button class="ct3-close" aria-label="Close">×</button></div><div class="ct3-body"><div class="ct3-card"><h3>Role context</h3><div class="ct3-muted" style="margin-bottom:8px">Role selections are stored locally in this browser. The public application does not need a private repository or personal account token.</div><div class="ct-career-selects"><div><label>Current role<select data-role="current">${roleOptions(ctx.current)}</select></label></div><div><label>Next role<select data-role="next">${roleOptions(ctx.next)}</select></label></div><div><label>Long-term target<select data-role="target">${roleOptions(ctx.target)}</select></label></div></div></div><div class="ct3-grid" style="margin-top:12px"><div class="ct3-card"><h3>Best to do now</h3>${(picks.now||[]).map(row).join('')||'<div class="ct3-muted">No available certifications.</div>'}</div><div class="ct3-card"><h3>Best for next role</h3>${(picks.next||[]).map(row).join('')||'<div class="ct3-muted">No available certifications.</div>'}</div></div><div class="ct3-card" style="margin-top:12px"><h3>Best long-term investments</h3>${(picks.long||[]).map(row).join('')||'<div class="ct3-muted">No available certifications.</div>'}</div><div class="ct3-notice">M = credential-market value. K = real deployment/troubleshooting/design knowledge. C/N/E change with the selected role context. T3 items are experience-gated; a certificate is not a substitute for senior practical responsibility.</div></div></section>`;
    root.querySelector('.ct3-close').addEventListener('click',()=>close(root));root.addEventListener('mousedown',e=>{if(e.target===root)close(root);});root.querySelectorAll('[data-role]').forEach(sel=>sel.addEventListener('change',()=>{CT.careerFramework.setContext({[sel.dataset.role]:sel.value});close(root);open();}));document.body.appendChild(root);root.querySelector('.ct3-close').focus();}
  function init(){injectStyle();if(document.getElementById('ct-career-launcher'))return;const b=document.createElement('button');b.id='ct-career-launcher';b.type='button';b.textContent='Career';b.setAttribute('aria-label','Open career decision model');b.addEventListener('click',open);document.body.appendChild(b);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();CT.careerUI=Object.freeze({open});
})(window);
