// Cert Tracker — generic role-aware career, capability and evidence interface.
// Personal career data should remain outside the public repository.
(function initCareerUI(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.careerFramework||!CT?.recommendations)return;const esc=CT.util.escapeHtml;
  function injectStyle(){if(document.getElementById('ct-career-style'))return;const s=document.createElement('style');s.id='ct-career-style';s.textContent=`#ct-career-launcher{position:fixed;left:92px;bottom:18px;z-index:9997;border:1px solid rgba(255,255,255,.18);background:rgba(23,17,48,.94);color:#fff;border-radius:999px;padding:10px 14px;font:600 12px/1 ui-sans-serif,system-ui,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.32);cursor:pointer;backdrop-filter:blur(14px)}.ct-career-score{display:grid;grid-template-columns:repeat(6,minmax(48px,1fr));gap:6px;margin-top:8px}.ct-career-score>span{border:1px solid rgba(255,255,255,.09);border-radius:8px;padding:7px 4px;text-align:center;font:700 11px ui-monospace,monospace}.ct-career-score small{display:block;margin-top:3px;color:#aaa4c8;font:500 9px ui-sans-serif,system-ui,sans-serif}.ct-career-selects{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ct-career-selects label{font-size:10px;color:#aaa4c8}.ct-career-selects select,.ct-evidence-row select{width:100%;margin-top:4px;background:#0f0b22;border:1px solid rgba(255,255,255,.14);color:#fff;border-radius:8px;padding:8px;font:600 11px ui-sans-serif,system-ui,sans-serif}.ct-pillar-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}.ct-pillar{border:1px solid rgba(255,255,255,.09);border-radius:10px;padding:10px}.ct-pillar strong{display:flex;justify-content:space-between;gap:8px}.ct-meter{height:5px;background:rgba(255,255,255,.08);border-radius:999px;overflow:hidden;margin-top:7px}.ct-meter>i{display:block;height:100%;background:currentColor}.ct-gate{border-top:1px solid rgba(255,255,255,.08);padding:10px 0}.ct-gate:first-child{border-top:0}.ct-gate-head{display:flex;justify-content:space-between;gap:10px}.ct-evidence-row{display:grid;grid-template-columns:minmax(0,1fr) 170px;gap:10px;align-items:center;padding:8px 0;border-top:1px solid rgba(255,255,255,.06)}.ct-evidence-row:first-child{border-top:0}.ct-evidence-group summary{cursor:pointer;font-weight:700;padding:8px 0}.ct-tag{display:inline-block;border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:3px 7px;margin-top:5px;font-size:9px;color:#c8c2df}@media(max-width:640px){#ct-career-launcher{left:82px;bottom:12px}.ct-career-selects{grid-template-columns:1fr}.ct-career-score{grid-template-columns:repeat(3,1fr)}.ct-evidence-row{grid-template-columns:1fr}.ct3-panel{max-height:92vh;overflow:auto}}`;document.head.appendChild(s);}
  function roleOptions(selected){return Object.entries(CT.careerFramework.ROLE_PROFILES).map(([key,p])=>`<option value="${esc(key)}"${key===selected?' selected':''}>${esc(p.label)}</option>`).join('');}
  function scoreHtml(card){return `<div class="ct-career-score"><span>M${card.M}<small>MARKET</small></span><span>K${card.K}<small>KNOWLEDGE</small></span><span>C${card.C}<small>CURRENT</small></span><span>N${card.N}<small>NEXT</small></span><span>E${card.E}<small>ENDGAME</small></span><span>${esc(card.T)}<small>TIMING</small></span></div>`;}
  function row(item){const gate=item.experienceGate&&!item.experienceGate.ready?`<div class="ct3-muted">Role gate ${item.experienceGate.score}% — ${esc(item.experienceGate.label)}</div>`:'';return `<div class="ct3-row"><div style="flex:1"><strong>${esc(item.name)}</strong><div class="ct-tag">${esc(item.portfolioClass||'SUPPORTING')}</div><div class="ct3-muted">${esc((item.reasons||[]).slice(0,2).join(' · '))}</div>${gate}${scoreHtml(item.career)}</div><div style="text-align:right"><strong>${esc(item.marketValue?.contributionLabel||'n/a')}</strong><div class="ct3-muted">opportunity signal</div></div></div>`;}
  function levelOptions(current){return Object.entries(CT.capabilityGates.LEVELS).map(([key,value])=>`<option value="${key}"${key===current?' selected':''}>${esc(value.label)}</option>`).join('');}
  function pillarHtml(snapshot){return Object.values(snapshot).map(p=>`<div class="ct-pillar"><strong><span>${esc(p.label)}</span><span>${p.score}%</span></strong><div class="ct-meter"><i style="width:${p.score}%"></i></div><div class="ct3-muted" style="margin-top:6px">Knowledge + practical evidence</div></div>`).join('');}
  function gateHtml(gate){const blockers=gate.ready?'Ready for this transition':gate.blockers.slice(0,3).join(' · ');return `<div class="ct-gate"><div class="ct-gate-head"><strong>${esc(gate.label)}</strong><strong>${gate.score}%${gate.ready?' ✓':''}</strong></div><div class="ct-meter"><i style="width:${gate.score}%"></i></div><div class="ct3-muted" style="margin-top:6px">${esc(blockers)}</div></div>`;}
  function evidenceGroups(){const groups={};for(const item of CT.capabilityGates.EVIDENCE){(groups[item.pillar]||(groups[item.pillar]=[])).push(item);}return Object.entries(groups).map(([pillar,items])=>`<details class="ct-evidence-group"><summary>${esc(CT.capabilityGates.PILLARS[pillar]?.label||pillar)} · ${CT.capabilityGates.pillarScore(pillar)}%</summary>${items.map(item=>{const record=CT.capabilityGates.evidenceRecord(item.id);return `<div class="ct-evidence-row"><div><strong>${esc(item.label)}</strong><div class="ct3-muted">Evidence maturity: ${esc(CT.capabilityGates.LEVELS[record.level].label)}</div></div><select data-evidence="${esc(item.id)}" aria-label="Evidence maturity for ${esc(item.label)}">${levelOptions(record.level)}</select></div>`;}).join('')}</details>`).join('');}
  function close(root){root?.remove();}
  function open(){
    const existing=document.getElementById('ct-career-modal');if(existing){existing.remove();return;}
    const ctx=CT.careerFramework.context();const picks=CT.recommendations.recommendationsByHorizon({limit:3});const pillars=CT.capabilityGates?.pillarSnapshot?.()||{};const gates=CT.capabilityGates?.allRoleGates?.()||[];
    const root=document.createElement('div');root.id='ct-career-modal';root.className='ct3-backdrop';root.innerHTML=`<section class="ct3-panel" role="dialog" aria-modal="true" aria-label="Career decision model"><div class="ct3-head"><div><div class="ct3-title">Career capability model</div><div class="ct3-sub">Certifications + practical evidence + role-transition readiness</div></div><button class="ct3-close" aria-label="Close">×</button></div><div class="ct3-body">
      <div class="ct3-card"><h3>Role context</h3><div class="ct3-muted" style="margin-bottom:8px">Role selections and practical evidence are stored locally and included in encrypted device-state backups. The public repository contains only generic logic.</div><div class="ct-career-selects"><div><label>Current role<select data-role="current">${roleOptions(ctx.current)}</select></label></div><div><label>Next role<select data-role="next">${roleOptions(ctx.next)}</select></label></div><div><label>Long-term target<select data-role="target">${roleOptions(ctx.target)}</select></label></div></div></div>
      <div class="ct3-card" style="margin-top:12px"><h3>Capability pillars</h3><div class="ct3-muted" style="margin-bottom:8px">A certificate increases knowledge signal; maturity rises further when the skill is labbed, used, designed and eventually owned.</div><div class="ct-pillar-grid">${pillarHtml(pillars)}</div></div>
      <div class="ct3-card" style="margin-top:12px"><h3>Role transition gates</h3>${gates.map(gateHtml).join('')}</div>
      <div class="ct3-grid" style="margin-top:12px"><div class="ct3-card"><h3>Best to do now</h3>${(picks.now||[]).map(row).join('')||'<div class="ct3-muted">No available certifications.</div>'}</div><div class="ct3-card"><h3>Best for next role</h3>${(picks.next||[]).map(row).join('')||'<div class="ct3-muted">No available certifications.</div>'}</div></div>
      <div class="ct3-card" style="margin-top:12px"><h3>Best long-term investments</h3>${(picks.long||[]).map(row).join('')||'<div class="ct3-muted">No available certifications.</div>'}</div>
      <div class="ct3-card" style="margin-top:12px"><h3>Practical evidence gates</h3><div class="ct3-muted">Use the maturity level that reflects what you can actually evidence. A lab is not the same as production use; production use is not the same as designing or owning the solution.</div>${CT.capabilityGates?evidenceGroups():'<div class="ct3-muted">Capability model unavailable.</div>'}</div>
      <div class="ct3-notice">M = credential-market value. K = practical knowledge. C/N/E change with role context. T3 and capstone credentials are suppressed from near-term planning when their role/experience gates are not met. The tracker is designed to reward progression from learning → labbing → real use → design → ownership, not exam velocity alone.</div>
    </div></section>`;
    root.querySelector('.ct3-close').addEventListener('click',()=>close(root));root.addEventListener('mousedown',e=>{if(e.target===root)close(root);});
    root.querySelectorAll('[data-role]').forEach(sel=>sel.addEventListener('change',()=>{CT.careerFramework.setContext({[sel.dataset.role]:sel.value});close(root);open();}));
    root.querySelectorAll('[data-evidence]').forEach(sel=>sel.addEventListener('change',()=>{CT.capabilityGates.setEvidence(sel.dataset.evidence,sel.value);close(root);open();}));
    document.body.appendChild(root);root.querySelector('.ct3-close').focus();
  }
  function init(){injectStyle();if(document.getElementById('ct-career-launcher'))return;const b=document.createElement('button');b.id='ct-career-launcher';b.type='button';b.textContent='Career';b.setAttribute('aria-label','Open career capability model');b.addEventListener('click',open);document.body.appendChild(b);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();CT.careerUI=Object.freeze({open});
})(window);
