// Cert Tracker — readiness and constraint-aware planning interface.
(function initIntelligenceUI(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.planner)return;
  const esc=CT.util.escapeHtml;
  function style(){if(document.getElementById('ct-intel-style'))return;const el=document.createElement('style');el.id='ct-intel-style';el.textContent=`#ct-intel-launcher{position:fixed;left:18px;bottom:18px;z-index:9997;border:1px solid rgba(255,255,255,.18);background:rgba(23,17,48,.94);color:#fff;border-radius:999px;padding:10px 14px;font:600 12px/1 ui-sans-serif,system-ui,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.32);cursor:pointer;backdrop-filter:blur(14px)}.ct-intel-meter{height:7px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden;margin-top:7px}.ct-intel-meter>i{display:block;height:100%;background:currentColor}.ct-intel-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}.ct-intel-kpis>div{padding:9px;border:1px solid rgba(255,255,255,.09);border-radius:9px;text-align:center}.ct-intel-kpis strong{display:block;font:700 14px ui-monospace,monospace}.ct-intel-kpis span{font-size:10px;color:#aaa4c8}.ct-intel-objective{display:flex;align-items:center;gap:6px;margin-top:7px}.ct-intel-objective label{font-size:10px;color:#aaa4c8}.ct-intel-objective input{width:66px;background:#0f0b22;border:1px solid rgba(255,255,255,.14);color:#fff;border-radius:7px;padding:5px 6px;font:600 11px ui-monospace,monospace}@media(max-width:640px){.ct-intel-kpis{grid-template-columns:repeat(2,1fr)}#ct-intel-launcher{left:12px;bottom:12px}}`;document.head.appendChild(el);}
  function close(root){root?.remove();}
  function currentRows(){return CT.recommendations.recommend({limit:6}).map(item=>({...item,ready:CT.competency.readiness(item.cert,CT.recommendations.currentGoal())}));}
  function open(){const old=document.getElementById('ct-intel-modal');if(old){old.remove();return;}const settings=CT.planner.settings();const plan=CT.planner.plan();const path=CT.phases.pathStatus();const coverage=CT.competency.goalCoverage(CT.recommendations.currentGoal());const rows=currentRows();const root=document.createElement('div');root.id='ct-intel-modal';root.className='ct3-backdrop';root.innerHTML=`<section class="ct3-panel" role="dialog" aria-modal="true" aria-label="Readiness and plan"><div class="ct3-head"><div><div class="ct3-title">Readiness & plan</div><div class="ct3-sub">Competency gaps, remaining effort and an optimised sequence</div></div><button class="ct3-close" aria-label="Close">×</button></div><div class="ct3-body">
    <div class="ct-intel-kpis"><div><strong>${coverage.score}%</strong><span>ROLE COVERAGE</span></div><div><strong>${path.complete?'DONE':`P${path.currentPhase}`}</strong><span>PATH STATUS</span></div><div><strong>${plan.usedHours}h</strong><span>PLANNED EFFORT</span></div><div><strong>${CT.marketValue.money(plan.usedBudget)}</strong><span>SELF-FUNDED</span></div></div>
    <div class="ct3-grid"><div class="ct3-card"><h3>Planning constraints</h3><div class="ct3-field"><label>Study hours / week</label><input id="ct-plan-hours" type="number" min="0.5" max="168" step="0.5" value="${settings.weeklyHours}"></div><div class="ct3-field"><label>Budget (£, blank = unrestricted)</label><input id="ct-plan-budget" type="number" min="0" step="25" value="${Number.isFinite(settings.budget)?settings.budget:''}"></div><div class="ct3-field"><label>Target date</label><input id="ct-plan-date" type="date" value="${esc(settings.targetDate)}"></div><div class="ct3-field"><label>Maximum certifications</label><input id="ct-plan-max" type="number" min="1" max="30" value="${settings.maxCerts}"></div><button class="ct3-btn primary" id="ct-plan-run">Recalculate plan</button></div>
    <div class="ct3-card"><h3>Largest competency gaps</h3>${coverage.gaps.slice(0,7).map(g=>`<div class="ct3-row"><div style="flex:1"><strong>${esc(g.label)}</strong><div class="ct-intel-meter"><i style="width:${Math.round(g.level*100)}%"></i></div></div><span class="ct3-pill">${Math.round(g.level*100)}%</span></div>`).join('')}</div></div>
    <div class="ct3-card" style="margin-top:12px"><h3>Readiness now</h3><div class="ct3-muted" style="margin-bottom:8px">Objective coverage is optional. Enter a current percentage from the official exam objectives or practice tracking to improve the readiness estimate.</div>${rows.map(item=>`<div class="ct3-row"><div><strong>${esc(item.name)}</strong><div class="ct3-muted">${item.ready.remainingHours}h estimated remaining · target fit ${item.relevance.percent}% · marginal value ${esc(item.marketValue?.contributionLabel||'n/a')}</div><div class="ct-intel-objective"><label for="ct-objective-${esc(item.id)}">Objectives</label><input id="ct-objective-${esc(item.id)}" data-objective="${esc(item.id)}" type="number" min="0" max="100" step="5" value="${Math.round(CT.store.objective(item.id))}" aria-label="${esc(item.name)} objective coverage percentage"><span class="ct3-muted">%</span></div></div><span class="ct3-pill">${item.ready.score}% ready</span></div>`).join('')||'<div class="ct3-muted">No available certifications.</div>'}</div>
    <div class="ct3-card" style="margin-top:12px"><h3>Optimised sequence</h3><div class="ct3-muted" style="margin-bottom:8px">Projected target-role coverage ${plan.baselineCoverage}% → ${plan.projectedCoverage}% (+${plan.coverageGain}).</div>${plan.sequence.map(item=>`<div class="ct3-row"><div><strong>${item.position}. ${esc(item.name)}</strong><div class="ct3-muted">ETA ${item.eta} · ${item.hours}h · ${item.cost?CT.marketValue.money(item.cost):'funded/free'} · ${item.readiness}% ready</div></div><div style="text-align:right"><strong>${esc(item.marginalLabel)}</strong><div class="ct3-muted">marginal signal</div></div></div>`).join('')||'<div class="ct3-muted">No sequence fits the current constraints.</div>'}</div>
    <div class="ct3-notice">Readiness is an estimate derived from prerequisites, logged study, objective progress, existing competency coverage and exam status. It is not a guarantee of an exam pass.</div>
    </div></section>`;
    root.querySelector('.ct3-close').addEventListener('click',()=>close(root));root.addEventListener('mousedown',e=>{if(e.target===root)close(root);});root.querySelector('#ct-plan-run').addEventListener('click',()=>{CT.planner.saveSettings({weeklyHours:Number(root.querySelector('#ct-plan-hours').value),budget:root.querySelector('#ct-plan-budget').value,targetDate:root.querySelector('#ct-plan-date').value,maxCerts:Number(root.querySelector('#ct-plan-max').value)});close(root);open();});root.querySelectorAll('[data-objective]').forEach(input=>input.addEventListener('change',()=>{CT.store.setObjective(input.dataset.objective,Number(input.value));close(root);open();}));document.body.appendChild(root);root.querySelector('.ct3-close').focus();}
  function init(){style();if(document.getElementById('ct-intel-launcher'))return;const button=document.createElement('button');button.id='ct-intel-launcher';button.type='button';button.textContent='Plan';button.setAttribute('aria-label','Open readiness and planning');button.addEventListener('click',open);document.body.appendChild(button);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  CT.intelligenceUI=Object.freeze({open});
})(window);
