// Cert Tracker — readiness, practical capability and learning-first planning interface.
(function initIntelligenceUI(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.planner)return;
  const esc=CT.util.escapeHtml;
  function style(){if(document.getElementById('ct-intel-style'))return;const el=document.createElement('style');el.id='ct-intel-style';el.textContent=`#ct-intel-launcher{position:fixed;left:18px;bottom:18px;z-index:9997;border:1px solid rgba(255,255,255,.18);background:rgba(23,17,48,.94);color:#fff;border-radius:999px;padding:10px 14px;font:600 12px/1 ui-sans-serif,system-ui,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.32);cursor:pointer;backdrop-filter:blur(14px)}.ct-intel-meter{height:7px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden;margin-top:7px}.ct-intel-meter>i{display:block;height:100%;background:currentColor}.ct-intel-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:10px 0}.ct-intel-kpis>div{padding:9px;border:1px solid rgba(255,255,255,.09);border-radius:9px;text-align:center}.ct-intel-kpis strong{display:block;font:700 14px ui-monospace,monospace}.ct-intel-kpis span{font-size:10px;color:#aaa4c8}.ct-intel-objective{display:flex;align-items:center;gap:6px;margin-top:7px}.ct-intel-objective label{font-size:10px;color:#aaa4c8}.ct-intel-objective input{width:66px;background:#0f0b22;border:1px solid rgba(255,255,255,.14);color:#fff;border-radius:7px;padding:5px 6px;font:600 11px ui-monospace,monospace}@media(max-width:760px){.ct-intel-kpis{grid-template-columns:repeat(2,1fr)}#ct-intel-launcher{left:12px;bottom:12px}}`;document.head.appendChild(el);}
  function close(root){root?.remove();}
  function currentRows(){return CT.recommendations.recommend({limit:6,horizon:'now'}).map(item=>({...item,ready:CT.competency.readiness(item.cert,CT.recommendations.currentGoal())}));}
  function nextGate(){if(!CT.capabilityGates||!CT.careerFramework)return null;const next=CT.careerFramework.context().next;const map={physicalSystemsEngineer:'physicalSystemsEngineer',networkSecurity:'networkSecurityEngineer',otSecurity:'otSecurityEngineer',convergenceEngineer:'convergenceEngineer',solutionsArchitect:'solutionsArchitect',securityArchitect:'solutionsArchitect',convergence:'principalConvergenceArchitect',principalConvergence:'principalConvergenceArchitect'};return map[next]?CT.capabilityGates.roleGateStatus(map[next]):null;}
  function capabilityGaps(){if(!CT.capabilityGates)return[];return Object.values(CT.capabilityGates.pillarSnapshot()).sort((a,b)=>a.score-b.score).slice(0,7);}
  function open(){const old=document.getElementById('ct-intel-modal');if(old){old.remove();return;}const settings=CT.planner.settings();const plan=CT.planner.plan();const path=CT.phases.pathStatus();const coverage=CT.competency.goalCoverage(CT.recommendations.currentGoal());const rows=currentRows();const top=rows[0]||null;const topic=CT.topicEngine?.next?.({cert:top?.cert||null})||null;const gate=nextGate();const pillars=capabilityGaps();const root=document.createElement('div');root.id='ct-intel-modal';root.className='ct3-backdrop';root.innerHTML=`<section class="ct3-panel" role="dialog" aria-modal="true" aria-label="Readiness and plan"><div class="ct3-head"><div><div class="ct3-title">Readiness & plan</div><div class="ct3-sub">Learning-first sequencing, practical evidence, role gates and constraints</div></div><button class="ct3-close" aria-label="Close">×</button></div><div class="ct3-body">
    <div class="ct-intel-kpis"><div><strong>${coverage.score}%</strong><span>ROLE KNOWLEDGE</span></div><div><strong>${gate?`${gate.score}%`:'—'}</strong><span>NEXT ROLE GATE</span></div><div><strong>${path.complete?'DONE':`P${path.currentPhase}`}</strong><span>PATH STATUS</span></div><div><strong>${plan.usedHours}h</strong><span>PLANNED EFFORT</span></div><div><strong>${CT.marketValue.money(plan.usedBudget)}</strong><span>SELF-FUNDED</span></div></div>
    <div class="ct3-grid"><div class="ct3-card"><h3>Next certification</h3>${top?`<div class="ct3-big">${esc(top.name)}</div><div class="ct3-muted">K${top.career.K} knowledge · M${top.career.M} market · ${top.ready.score}% exam ready · ~${top.ready.remainingHours}h remaining</div><div class="ct3-notice">${esc(top.reasons.slice(0,3).join(' · '))}</div>`:'<div class="ct3-muted">No available certification recommendation.</div>'}</div><div class="ct3-card"><h3>Study alongside it</h3>${topic?`<div class="ct3-big" style="font-size:20px">${esc(topic.topic.title)}</div><div class="ct3-muted">${topic.mastery}% evidenced · ${topic.certSynergy}% certification synergy</div><div class="ct3-notice">${esc(topic.topic.why)}</div>${topic.topic.actions.slice(0,2).map(a=>`<div class="ct3-muted" style="margin-top:5px">→ ${esc(a)}</div>`).join('')}`:'<div class="ct3-muted">No priority topic gap detected.</div>'}</div></div>
    ${gate?`<div class="ct3-notice"><strong>${esc(gate.label)} gate: ${gate.score}%${gate.ready?' — ready':' — not yet ready'}</strong><br>${esc(gate.ready?'All generic capability/evidence thresholds are currently met.':gate.blockers.slice(0,3).join(' · '))}</div>`:''}
    <div class="ct3-grid"><div class="ct3-card"><h3>Planning constraints</h3><div class="ct3-field"><label>Study hours / week</label><input id="ct-plan-hours" type="number" min="0.5" max="168" step="0.5" value="${settings.weeklyHours}"></div><div class="ct3-field"><label>Budget (£, blank = unrestricted)</label><input id="ct-plan-budget" type="number" min="0" step="25" value="${Number.isFinite(settings.budget)?settings.budget:''}"></div><div class="ct3-field"><label>Target date</label><input id="ct-plan-date" type="date" value="${esc(settings.targetDate)}"></div><div class="ct3-field"><label>Maximum certifications</label><input id="ct-plan-max" type="number" min="1" max="30" value="${settings.maxCerts}"></div><button class="ct3-btn primary" id="ct-plan-run">Recalculate plan</button></div>
    <div class="ct3-card"><h3>Lowest practical capability pillars</h3>${pillars.map(g=>`<div class="ct3-row"><div style="flex:1"><strong>${esc(g.label)}</strong><div class="ct-intel-meter"><i style="width:${g.score}%"></i></div></div><span class="ct3-pill">${g.score}%</span></div>`).join('')}</div></div>
    <div class="ct3-card" style="margin-top:12px"><h3>Largest knowledge gaps</h3>${coverage.gaps.slice(0,7).map(g=>`<div class="ct3-row"><div style="flex:1"><strong>${esc(g.label)}</strong><div class="ct-intel-meter"><i style="width:${Math.round(g.level*100)}%"></i></div></div><span class="ct3-pill">${Math.round(g.level*100)}%</span></div>`).join('')}</div>
    <div class="ct3-card" style="margin-top:12px"><h3>Readiness now</h3><div class="ct3-muted" style="margin-bottom:8px">Knowledge and curriculum value lead the recommendation. Market value is retained as a secondary signal. Practical role gates are scored separately.</div>${rows.map(item=>`<div class="ct3-row"><div><strong>${esc(item.name)}</strong><div class="ct3-muted">K${item.career.K} · M${item.career.M} · ${item.ready.remainingHours}h estimated remaining · target fit ${item.relevance.percent}% · ${esc(item.portfolioClass||'Supporting')}</div><div class="ct-intel-objective"><label for="ct-objective-${esc(item.id)}">Objectives</label><input id="ct-objective-${esc(item.id)}" data-objective="${esc(item.id)}" type="number" min="0" max="100" step="5" value="${Math.round(CT.store.objective(item.id))}" aria-label="${esc(item.name)} objective coverage percentage"><span class="ct3-muted">%</span></div></div><span class="ct3-pill">${item.ready.score}% exam ready</span></div>`).join('')||'<div class="ct3-muted">No available certifications.</div>'}</div>
    <div class="ct3-card" style="margin-top:12px"><h3>Learning-first sequence</h3><div class="ct3-muted" style="margin-bottom:8px">Projected target-role knowledge ${plan.baselineCoverage}% → ${plan.projectedCoverage}% (+${plan.coverageGain}). Curriculum depth and ladder continuity outrank market signal; unmet T3 experience gates are excluded.</div>${plan.sequence.map(item=>`<div class="ct3-row"><div><strong>${item.position}. ${esc(item.name)}</strong><div class="ct3-muted">K${item.knowledgeValue||'—'} · ETA ${item.eta} · ${item.hours}h · ${item.cost?CT.marketValue.money(item.cost):'funded/free'} · ${item.readiness}% exam ready · ${esc(item.portfolioClass||'Supporting')}</div></div><div style="text-align:right"><strong>${esc(item.marginalLabel)}</strong><div class="ct3-muted">secondary market signal</div></div></div>`).join('')||'<div class="ct3-muted">No sequence fits the current constraints.</div>'}</div>
    <div class="ct3-notice">The planner separates study/certification progress from practical career readiness. Use Learning Path for the phase-by-phase curriculum view and Career to record evidence maturity from Labbed → Used → Designed → Owned.</div>
    </div></section>`;
    root.querySelector('.ct3-close').addEventListener('click',()=>close(root));root.addEventListener('mousedown',e=>{if(e.target===root)close(root);});root.querySelector('#ct-plan-run').addEventListener('click',()=>{CT.planner.saveSettings({weeklyHours:Number(root.querySelector('#ct-plan-hours').value),budget:root.querySelector('#ct-plan-budget').value,targetDate:root.querySelector('#ct-plan-date').value,maxCerts:Number(root.querySelector('#ct-plan-max').value)});close(root);open();});root.querySelectorAll('[data-objective]').forEach(input=>input.addEventListener('change',()=>{CT.store.setObjective(input.dataset.objective,Number(input.value));close(root);open();}));document.body.appendChild(root);root.querySelector('.ct3-close').focus();}
  function init(){style();if(document.getElementById('ct-intel-launcher'))return;const button=document.createElement('button');button.id='ct-intel-launcher';button.type='button';button.textContent='Plan';button.setAttribute('aria-label','Open readiness and learning plan');button.addEventListener('click',open);document.body.appendChild(button);CT.personalization?.organiseDock?.();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  CT.intelligenceUI=Object.freeze({open});
})(window);
