// Cert Tracker — privacy-preserving live job-market feed and best-fit matching.
(function initJobMarket(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.marketReadiness)return;
  let cache=null,loading=null;
  const FEED='data/job-market.json';
  const STOP=new Set(['and','the','for','with','security','engineer','analyst','specialist','manager','uk','cyber']);
  function words(value){return [...new Set(String(value||'').toLowerCase().replace(/[^a-z0-9+#/. -]+/g,' ').split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)))];}
  function overlap(a,b){const A=words(a),B=new Set(words(b));if(!A.length)return 0;return A.filter(x=>B.has(x)||[...B].some(y=>y.includes(x)||x.includes(y))).length/A.length;}
  function ageScore(created){if(!created)return 30;const days=(Date.now()-new Date(created).getTime())/86400000;if(!Number.isFinite(days))return 20;return Math.max(0,100-days*9);}
  function salaryMid(job){const lo=Number(job.salaryMin)||0,hi=Number(job.salaryMax)||0;return lo&&hi?(lo+hi)/2:lo||hi||0;}
  function providerSearch(role,provider){const q=encodeURIComponent(role?.query||role?.label||'cyber security');if(provider==='indeed')return`https://uk.indeed.com/jobs?q=${q}`;if(provider==='reed')return`https://www.reed.co.uk/jobs/${q.replace(/%20/g,'-')}-jobs`;return`https://www.adzuna.co.uk/search?q=${q}`;}
  async function load({force=false}={}){if(cache&&!force)return cache;if(loading&&!force)return loading;loading=fetch(`${FEED}?v=${Date.now()}`,{cache:'no-store',credentials:'same-origin'}).then(r=>{if(!r.ok)throw new Error(`Market feed HTTP ${r.status}`);return r.json();}).then(data=>{cache=data;return data;}).catch(error=>{console.warn('[CertTracker job market]',error);return cache||{schemaVersion:1,status:'unavailable',jobs:[],fetchedAt:null,provider:'Adzuna'};}).finally(()=>{loading=null;});return loading;}
  function roleForJob(job,roles=CT.marketReadiness.roles()){const text=`${job.query||''} ${job.title||''} ${job.description||''}`;return roles.map(role=>{const direct=Math.max(overlap(role.query,text),overlap(role.label,text)),path=role.path?.spec?.mission?overlap(role.path.spec.mission,text):0;return{role,match:Math.max(direct,path*.8)};}).sort((a,b)=>b.match-a.match||b.role.score-a.role.score)[0]||null;}
  function rankJobs(feed,roles=CT.marketReadiness.roles()){return Object.freeze((feed?.jobs||[]).map(job=>{const linked=roleForJob(job,roles),role=linked?.role,match=linked?.match||0,salary=salaryMid(job),marketMedian=Number(role?.market?.median)||1,salaryFit=salary?Math.min(100,salary/marketMedian*75):50;const score=Math.round((role?.score||0)*.58+match*100*.26+ageScore(job.created)*.10+salaryFit*.06);return Object.freeze({job,role,roleMatch:Math.round(match*100),score,salaryMid:salary});}).filter(x=>x.roleMatch>=22).sort((a,b)=>b.score-a.score||b.roleMatch-a.roleMatch||String(b.job.created||'').localeCompare(String(a.job.created||''))).slice(0,40));}
  function liveBand(role,feed=cache){const rows=rankJobs(feed,[role]).filter(x=>x.roleMatch>=38).map(x=>x.salaryMid).filter(x=>x>=20000&&x<=250000).sort((a,b)=>a-b);if(rows.length<3)return null;const pct=p=>rows[Math.min(rows.length-1,Math.floor((rows.length-1)*p))];return Object.freeze({low:Math.round(pct(.2)/500)*500,median:Math.round(pct(.5)/500)*500,high:Math.round(pct(.8)/500)*500,samples:rows.length,source:feed?.provider||'live feed',fetchedAt:feed?.fetchedAt||null});}
  function bestFit(feed=cache,limit=10){return rankJobs(feed).filter(x=>x.role?.score>=45).slice(0,limit);}
  function summary(feed=cache){const roles=CT.marketReadiness.roles(),ranked=rankJobs(feed,roles),best=ranked.filter(x=>x.role?.score>=58);return Object.freeze({status:feed?.status||'unavailable',provider:feed?.provider||'Adzuna',fetchedAt:feed?.fetchedAt||null,total:Number(feed?.jobs?.length||0),bestFit:Object.freeze(best.slice(0,12)),ranked,roles:Object.freeze(roles.slice(0,12))});}
  CT.jobMarket=Object.freeze({FEED,load,rankJobs,roleForJob,liveBand,bestFit,summary,providerSearch,salaryMid});
})(window);
