// Cert Tracker — dedicated visual learning-path workspace.
(function initLearningPathUI(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.topicEngine||!CT?.recommendations||!CT?.capabilityGates)return;const esc=CT.util.escapeHtml;
  const PHASES=Object.freeze({
    1:{title:'Foundations + current-role depth',sub:'Physical-security systems, networking fundamentals and infrastructure underneath the application'},
    2:{title:'Enterprise networking + network security',sub:'Professional routing, firewalls, segmentation and resilient systems'},
    3:{title:'Cloud + identity + SecOps + automation',sub:'Hybrid networking, identity, defensive operations and programmable integration'},
    4:{title:'OT + convergence engineering',sub:'Industrial systems, OT cybersecurity, integration and architecture foundations'},
    5:{title:'Security + convergence architecture',sub:'Design ownership, cloud/security architecture, commercial decisions and specialist depth'},
    6:{title:'Principal / professional capstone',sub:'Experience-gated expert recognition, leadership and architecture ownership'}
  });
  const GATE_AFTER=Object.freeze({1:'physicalSystemsEngineer',2:'networkSecurityEngineer',3:'otSecurityEngineer',4:'convergenceEngineer',5:'solutionsArchitect',6:'principalConvergenceArchitect'});
  const timingRank={DONE:0,T0:1,T1:2,T2:3,T3:4};

  function pathCerts(phase){return CERTS.filter(c=>CT.store.effectivePhase(c)===phase&&state.myPath?.[c.id]).sort((a,b)=>{
    const ap=!!state.passes?.[a.id],bp=!!state.passes?.[b.id];if(ap!==bp)return ap?-1:1;
    const ac=CT.careerFramework.scoreCard(a),bc=CT.careerFramework.scoreCard(b);const ad=(a.deps||[]).filter(id=>!state.passes?.[id]).length,bd=(b.deps||[]).filter(id=>!state.passes?.[id]).length;if(ad!==bd)return ad-bd;
    if((timingRank[ac.T]??9)!==(timingRank[bc.T]??9))return (timingRank[ac.T]??9)-(timingRank[bc.T]??9);if(ac.K!==bc.K)return bc.K-ac.K;return a.name.localeCompare(b.name);
  });}
  function certItem(cert,nextId){const card=CT.careerFramework.scoreCard(cert);const cls=CT.capabilityGates.portfolioClass(cert,card);const done=!!state.passes?.[cert.id];const blocked=(cert.deps||[]).filter(id=>!state.passes?.[id]);const dot=done?'done':cert.id===nextId?'now':'';const detail=done?`Completed · ${cls}`:blocked.length?`Blocked by ${blocked.map(id=>CERTS.find(c=>c.id===id)?.code||id).join(', ')} · K${card.K} · ${card.T}`:`${cls} · K${card.K} · M${card.M} · ${card.T}`;return `<div class="ct-learning-item"><span class="ct-learning-dot ${dot}"></span><div><strong>${esc(cert.name)}</strong><small>${esc(detail)}</small></div></div>`;}
  function topicItem(row,nextTopicId){const now=row.topic.id===nextTopicId;return `<div class="ct-learning-item"><span class="ct-learning-dot ${now?'now':''}"></span><div><strong>${esc(row.topic.title)}</strong><small>${row.mastery}% evidenced · ${esc(row.reasons.slice(0,2).join(' · ')||row.topic.why)}</small></div></div>`;}
  function gateHtml(phase){const key=GATE_AFTER[phase],gate=key?CT.capabilityGates.roleGateStatus(key):null;if(!gate)return'';return `<div class="ct-learning-gate"><div><strong>ROLE GATE · ${esc(gate.label)}</strong><span>${esc(gate.ready?'Ready for transition':'Capability evidence required before treating this transition as ready')}</span></div><div><strong>${gate.score}%${gate.ready?' ✓':''}</strong><span>${esc(gate.ready?'Gate met':gate.blockers.slice(0,1).join(''))}</span></div></div>`;}
  function focusCardCert(item){if(!item)return `<div class="ct-learning-focus"><div class="ct-learning-eyebrow">Next certification</div><h2>No available recommendation</h2><p>The current path has no unblocked certification recommendation.</p></div>`;const c=item.career;return `<div class="ct-learning-focus"><div class="ct-learning-eyebrow">Next certification · learning-first</div><h2>${esc(item.name)}</h2><p>${esc(item.reasons.slice(0,3).join(' · '))}</p><div class="ct-learning-meta"><span class="ct-learning-chip">K${c.K} knowledge</span><span class="ct-learning-chip">M${c.M} market</span><span class="ct-learning-chip">${esc(c.T)} timing</span><span class="ct-learning-chip">${item.readiness.score}% exam ready</span></div></div>`;}
  function focusCardTopic(row,cert){if(!row)return `<div class="ct-learning-focus"><div class="ct-learning-eyebrow">Next topic</div><h2>No topic gap detected</h2><p>Build practical evidence for the current phase.</p></div>`;return `<div class="ct-learning-focus"><div class="ct-learning-eyebrow">Study alongside ${esc(cert?.code||'the next cert')}</div><h2>${esc(row.topic.title)}</h2><p>${esc(row.topic.why)}</p><div class="ct-learning-meta"><span class="ct-learning-chip">${row.mastery}% evidenced</span><span class="ct-learning-chip">${row.certSynergy}% cert synergy</span><span class="ct-learning-chip">Phase ${row.phase}</span></div><div style="margin-top:12px">${row.topic.actions.slice(0,3).map(x=>`<div class="ct3-muted" style="margin-top:5px">→ ${esc(x)}</div>`).join('')}</div></div>`;}
  function render(){
    const nextCert=CT.recommendations.recommend({limit:1,horizon:'now'})[0]||null;const nextTopic=CT.topicEngine.next({cert:nextCert?.cert||null});const nextId=nextCert?.id||'';const nextTopicId=nextTopic?.topic.id||'';
    const phaseBlocks=[];for(let p=1;p<=6;p++){const spec=PHASES[p],certs=pathCerts(p),topics=CT.topicEngine.forPhase(p,{cert:nextCert?.cert||null,limit:5});const completed=certs.filter(c=>state.passes?.[c.id]).length;phaseBlocks.push(`<div class="ct-learning-phase"><div class="ct-learning-phase-label"><strong>P${p}</strong><span>${completed}/${certs.length} certs</span></div><div class="ct-learning-phase-body"><div class="ct-learning-phase-head"><div><div class="ct-learning-phase-title">${esc(spec.title)}</div><div class="ct-learning-phase-sub">${esc(spec.sub)}</div></div><div class="ct-learning-chip">${completed}/${certs.length} complete</div></div><div class="ct-learning-columns"><div class="ct-learning-cert-list"><div class="ct-learning-section-label">Certification curriculum</div>${certs.length?certs.map(c=>certItem(c,nextId)).join(''):'<div class="ct3-muted">No certifications selected in this phase.</div>'}</div><div class="ct-learning-topic-list"><div class="ct-learning-section-label">Priority learning topics</div>${topics.length?topics.map(t=>topicItem(t,nextTopicId)).join(''):'<div class="ct3-muted">No active topic gaps for this phase.</div>'}</div></div></div></div>${gateHtml(p)}`);}
    return `<div class="ct-learning-workspace"><div class="ct3-card"><div class="ct3-title">Visual learning path</div><div class="ct3-sub">Curriculum → practical evidence → role gate. Knowledge value is weighted ahead of CV value.</div></div><div class="ct-learning-hero">${focusCardCert(nextCert)}${focusCardTopic(nextTopic,nextCert?.cert)}</div><div class="ct3-notice"><strong>How to read this path:</strong> certification order follows dependencies, timing and Knowledge ROI. Topics sit beside the certification curriculum so exam study and practical capability develop together. Role gates sit between phases and stop certification velocity being confused with career readiness.</div><div class="ct-learning-roadmap">${phaseBlocks.join('')}</div></div>`;
  }
  CT.learningPath=Object.freeze({render,PHASES,GATE_AFTER,pathCerts});
})(window);
