// Cert Tracker — dedicated customisation studio for visual and layout elements.
(function initPersonalizationUI(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.personalization)return;const esc=CT.util.escapeHtml;
  const COLOR_FIELDS=[['bg','Background'],['surface','Primary surface'],['surface2','Secondary surface'],['surface3','Raised surface'],['border','Border'],['border2','Strong border'],['text','Primary text'],['muted','Muted text'],['dim','Dim text'],['accent','Accent'],['success','Success'],['warning','Warning'],['danger','Danger'],['secondary','Secondary accent']];
  const PHASE_FIELDS=[['ph1','Phase 1'],['ph2','Phase 2'],['ph3','Phase 3'],['ph4','Phase 4'],['ph5','Phase 5'],['ph6','Phase 6']];
  const VIS_FIELDS=[['header','Header'],['navigation','Navigation'],['dashboard','Dashboard tab'],['learning','Learning Path tab'],['certifications','Certifications tab'],['strategy','Strategy tab'],['market','Market ROI tool'],['career','Career tool'],['plan','Plan tool'],['sync','Sync tool']];
  const TAB_KEYS=['dashboard','learning','certifications','strategy','customize'];

  function colorFields(s,fields,group){return fields.map(([key,label])=>`<div class="ct-custom-field"><label for="ct-custom-${group}-${key}">${esc(label)}</label><input id="ct-custom-${group}-${key}" type="color" data-custom-color="${group}.${key}" value="${esc((group==='colors'?s.colors:s.phaseColors)[key])}"></div>`).join('');}
  function rangeField(key,label,value,min,max,step,suffix=''){return `<div class="ct-custom-field"><label for="ct-custom-${key}">${esc(label)} <span class="ct3-muted" data-range-label="${key}">${esc(String(value))}${esc(suffix)}</span></label><input id="ct-custom-${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-custom-range="${key}" data-suffix="${esc(suffix)}"></div>`;}
  function toggleField(key,label,value,kind='root'){return `<div class="ct-custom-toggle"><label for="ct-custom-${kind}-${key}" class="ct3-muted">${esc(label)}</label><input id="ct-custom-${kind}-${key}" type="checkbox" data-custom-toggle="${kind}.${key}" ${value?'checked':''}></div>`;}
  function tabRows(s){return s.tabOrder.map((key,index)=>`<div class="ct3-row" data-tab-row="${esc(key)}"><div style="flex:1"><strong>${index+1}. ${esc(s.tabLabels[key]||key)}</strong><div class="ct3-muted">${esc(key)}</div></div><div class="ct3-actions" style="margin:0"><button class="ct3-btn" data-tab-move="up" data-tab="${esc(key)}" ${index===0?'disabled':''}>↑</button><button class="ct3-btn" data-tab-move="down" data-tab="${esc(key)}" ${index===s.tabOrder.length-1?'disabled':''}>↓</button></div></div>`).join('');}
  function render(){const s=CT.personalization.settings();const presets=Object.entries(CT.personalization.PRESETS).map(([key,p])=>`<button class="ct-preset${s.preset===key?' active':''}" data-preset="${esc(key)}"><strong>${esc(p.label)}</strong><span>${esc(p.description)}</span></button>`).join('');return `<div class="ct-learning-workspace"><div class="ct3-card"><div class="ct3-title">Tracker customisation</div><div class="ct3-sub">Professional defaults with user control over colour, typography, density, effects, visibility, navigation and labels. Settings are local and included in encrypted device sync.</div></div>
    <div class="ct-custom-group"><h3>Design presets</h3><div class="ct-preset-grid">${presets}</div><div class="ct3-actions"><button class="ct3-btn danger" data-custom-reset>Reset all customisation</button></div></div>
    <div class="ct-custom-grid">
      <div class="ct-custom-group"><h3>Core appearance</h3>${colorFields(s,COLOR_FIELDS,'colors')}</div>
      <div class="ct-custom-group"><h3>Phase colours</h3>${colorFields(s,PHASE_FIELDS,'phaseColors')}</div>
      <div class="ct-custom-group"><h3>Typography + geometry</h3>${rangeField('fontScale','Font scale',s.fontScale,.8,1.35,.05,'×')}${rangeField('density','Interface density',s.density,.72,1.3,.02,'×')}${rangeField('cardRadius','Card radius',s.cardRadius,0,28,1,'px')}${rangeField('controlRadius','Control radius',s.controlRadius,0,20,1,'px')}${rangeField('contentWidth','Content width',s.contentWidth,760,1800,20,'px')}${rangeField('borderWidth','Border width',s.borderWidth,0,3,.5,'px')}</div>
      <div class="ct-custom-group"><h3>Depth + effects</h3>${rangeField('panelOpacity','Panel opacity',s.panelOpacity,.72,1,.01,'')}${rangeField('shadowStrength','Shadow strength',s.shadowStrength,0,.75,.01,'')}${rangeField('glowStrength','Background glow',s.glowStrength,0,.5,.01,'')}${toggleField('animations','Animations',s.animations)}${toggleField('glass','Glass / blur',s.glass)}${toggleField('shadows','Shadows',s.shadows)}<div class="ct-custom-field"><label>Navigation density</label><select data-custom-select="navStyle"><option value="standard"${s.navStyle==='standard'?' selected':''}>Standard</option><option value="compact"${s.navStyle==='compact'?' selected':''}>Compact</option></select></div><div class="ct-custom-field"><label>Badge density</label><select data-custom-select="badgeStyle"><option value="standard"${s.badgeStyle==='standard'?' selected':''}>Standard</option><option value="compact"${s.badgeStyle==='compact'?' selected':''}>Compact</option></select></div></div>
      <div class="ct-custom-group"><h3>Element visibility</h3>${VIS_FIELDS.map(([key,label])=>toggleField(key,label,s.visibility[key]!==false,'visibility')).join('')}<div class="ct3-notice">Customize always remains available so hidden elements can be restored.</div></div>
      <div class="ct-custom-group"><h3>Tracker identity + labels</h3><div class="ct-custom-field"><label>Application title</label><input type="text" maxlength="40" data-custom-text="appTitle" value="${esc(s.appTitle)}"></div>${TAB_KEYS.map(key=>`<div class="ct-custom-field"><label>${esc(key)} label</label><input type="text" maxlength="28" data-tab-label="${esc(key)}" value="${esc(s.tabLabels[key]||key)}"></div>`).join('')}</div>
      <div class="ct-custom-group"><h3>Navigation order</h3><div class="ct3-muted" style="margin-bottom:7px">Reorder the dedicated workspaces. Customize cannot be hidden.</div>${tabRows(s)}</div>
    </div></div>`;}

  function patchPath(path,value){const [group,key]=path.split('.');if(key)return {[group]:{...CT.personalization.settings()[group],[key]:value}};return {[group]:value};}
  function bind(root){if(!root)return;root.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>CT.personalization.preset(b.dataset.preset)));
    root.querySelector('[data-custom-reset]')?.addEventListener('click',()=>{if(confirm('Reset all tracker customisation to the professional default?'))CT.personalization.reset();});
    root.querySelectorAll('[data-custom-color]').forEach(input=>input.addEventListener('input',()=>CT.personalization.update(patchPath(input.dataset.customColor,input.value))));
    root.querySelectorAll('[data-custom-range]').forEach(input=>input.addEventListener('input',()=>{const key=input.dataset.customRange,val=Number(input.value),label=root.querySelector(`[data-range-label="${key}"]`);if(label)label.textContent=`${val}${input.dataset.suffix||''}`;CT.personalization.update({[key]:val});}));
    root.querySelectorAll('[data-custom-toggle]').forEach(input=>input.addEventListener('change',()=>CT.personalization.update(patchPath(input.dataset.customToggle,input.checked))));
    root.querySelectorAll('[data-custom-select]').forEach(input=>input.addEventListener('change',()=>CT.personalization.update({[input.dataset.customSelect]:input.value})));
    root.querySelectorAll('[data-custom-text]').forEach(input=>input.addEventListener('change',()=>CT.personalization.update({[input.dataset.customText]:input.value.trim()||CT.personalization.DEFAULTS[input.dataset.customText]})));
    root.querySelectorAll('[data-tab-label]').forEach(input=>input.addEventListener('change',()=>{const s=CT.personalization.settings(),labels={...s.tabLabels,[input.dataset.tabLabel]:input.value.trim()||CT.personalization.DEFAULTS.tabLabels[input.dataset.tabLabel]};CT.personalization.update({tabLabels:labels});}));
    root.querySelectorAll('[data-tab-move]').forEach(button=>button.addEventListener('click',()=>{const s=CT.personalization.settings(),order=[...s.tabOrder],idx=order.indexOf(button.dataset.tab),delta=button.dataset.tabMove==='up'?-1:1,next=idx+delta;if(idx<0||next<0||next>=order.length)return;[order[idx],order[next]]=[order[next],order[idx]];CT.personalization.update({tabOrder:order});}));
  }
  CT.personalizationUI=Object.freeze({render,bind});
})(window);
