// Cert Tracker — optional encrypted multi-device sync with revision and ETag protection.
(function initSync(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.storage)throw new Error('storage.js must load before sync.js');
  const encoder=new TextEncoder(),decoder=new TextDecoder();const ITERATIONS=250000;let session=null,autoTimer=null;
  const C=CT.config;
  function bytesToBase64(bytes){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary);}
  function base64ToBytes(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
  function deviceId(){let id=localStorage.getItem(C.deviceKey);if(!id){id=crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(C.deviceKey,id);}return id;}
  async function digest(value){let input=value;if(value&&typeof value==='object'){input=JSON.parse(JSON.stringify(value));delete input.exportedAt;delete input.syncMeta;}const bytes=encoder.encode(typeof input==='string'?input:CT.util.stableStringify(input));return bytesToBase64(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)));}
  async function deriveKey(passphrase,salt,iterations=ITERATIONS){if(!global.crypto?.subtle)throw new Error('Encrypted sync requires Web Crypto.');if(String(passphrase||'').length<10)throw new Error('Use a sync passphrase of at least 10 characters.');const rounds=Number(iterations);if(!Number.isInteger(rounds)||rounds<1000||rounds>10000000)throw new Error('Invalid PBKDF2 iteration count.');const material=await crypto.subtle.importKey('raw',encoder.encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:rounds,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
  async function encryptPayload(payload,passphrase,options={}){const iterations=options.iterations==null?ITERATIONS:Number(options.iterations);const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(passphrase,salt,iterations);const ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(payload))));return {format:'certtracker-vault',version:CT.version.sync,algorithm:'AES-GCM-256',kdf:'PBKDF2-SHA256',iterations,salt:bytesToBase64(salt),iv:bytesToBase64(iv),ciphertext:bytesToBase64(ciphertext)};}
  async function decryptPayload(envelope,passphrase){if(!envelope||envelope.format!=='certtracker-vault')throw new Error('Not a Cert Tracker encrypted vault.');const key=await deriveKey(passphrase,base64ToBytes(envelope.salt),Number(envelope.iterations||ITERATIONS));let plaintext;try{plaintext=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(envelope.iv)},key,base64ToBytes(envelope.ciphertext));}catch{throw new Error('Unable to decrypt vault. Check the passphrase or file integrity.');}const payload=JSON.parse(decoder.decode(plaintext));const validation=CT.storage.validateBackup(payload);if(!validation.ok)throw new Error(`Decrypted vault is invalid: ${validation.errors.join(' ')}`);return payload;}
  function getConfig(){try{const value=JSON.parse(localStorage.getItem(C.syncConfigKey)||'{}');return {endpoint:value.endpoint||'',username:value.username||'',autoSync:!!value.autoSync};}catch{return {endpoint:'',username:'',autoSync:false};}}
  function setConfig(config){const endpoint=String(config?.endpoint||'').trim();if(endpoint&&!/^https:\/\//i.test(endpoint)&&!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\//i.test(endpoint))throw new Error('Sync endpoint must use HTTPS.');const clean={endpoint,username:String(config?.username||'').trim(),autoSync:!!config?.autoSync};localStorage.setItem(C.syncConfigKey,JSON.stringify(clean));CT.events.emit('sync-config-changed',clean);return clean;}
  function connect({password,passphrase}){if(!password)throw new Error('WebDAV password is required for this session.');if(String(passphrase||'').length<10)throw new Error('Sync passphrase must be at least 10 characters.');session={password:String(password),passphrase:String(passphrase)};CT.events.emit('sync-session',{connected:true});}
  function disconnect(){session=null;CT.events.emit('sync-session',{connected:false});}function isConnected(){return !!session;}
  function basicAuth(username,password){return `Basic ${bytesToBase64(encoder.encode(`${username}:${password}`))}`;}
  async function webdavRequest(method,{body=null,etag=null,createOnly=false}={}){const config=getConfig();if(!config.endpoint)throw new Error('Configure a WebDAV vault URL first.');if(!session)throw new Error('Connect this browser session before syncing.');const headers={Authorization:basicAuth(config.username,session.password),Accept:'application/json'};if(body!=null)headers['Content-Type']='application/json;charset=utf-8';if(etag)headers['If-Match']=etag;else if(createOnly)headers['If-None-Match']='*';return fetch(config.endpoint,{method,headers,body,cache:'no-store'});}
  async function makePayload(){const payload=CT.storage.serializableState();const revision=Math.max(0,Number(localStorage.getItem(C.syncRevisionKey)||0))+1;const syncMeta={deviceId:deviceId(),revision,contentHash:await digest(payload)};return {...payload,syncMeta};}
  async function readRemote(){const response=await webdavRequest('GET');if(response.status===404)return null;if(!response.ok)throw new Error(`WebDAV download failed (${response.status}).`);const envelope=await response.json();return {payload:await decryptPayload(envelope,session?.passphrase),etag:response.headers.get('ETag')||null};}
  function markCommon(payload,etag){localStorage.setItem(C.syncRevisionKey,String(payload?.syncMeta?.revision||0));if(payload?.syncMeta?.contentHash)localStorage.setItem(C.syncCommonHashKey,payload.syncMeta.contentHash);if(etag)localStorage.setItem(C.syncEtagKey,etag);else localStorage.removeItem(C.syncEtagKey);}
  async function push(options={}){let remote=null;if(!options.force)remote=await readRemote();const payload=await makePayload();const envelope=await encryptPayload(payload,session?.passphrase);const etag=remote?.etag||localStorage.getItem(C.syncEtagKey)||null;if(remote&&!options.force){const common=localStorage.getItem(C.syncCommonHashKey);const remoteHash=remote.payload?.syncMeta?.contentHash;const localHash=await digest(CT.storage.serializableState());if(common&&remoteHash&&remoteHash!==common&&localHash!==common){const error=new Error('Sync conflict: remote and local data both changed. Pull or force push explicitly.');error.code='SYNC_CONFLICT';throw error;}}
    const response=await webdavRequest('PUT',{body:JSON.stringify(envelope),etag:options.force?null:etag,createOnly:!remote&&!etag});if(response.status===409||response.status===412){const error=new Error('Sync conflict: the remote vault changed during upload.');error.code='SYNC_CONFLICT';throw error;}if(!response.ok)throw new Error(`WebDAV upload failed (${response.status}).`);markCommon(payload,response.headers.get('ETag')||etag);CT.events.emit('sync-complete',{direction:'push',changedAt:payload.changedAt});return {direction:'push',changedAt:payload.changedAt,revision:payload.syncMeta.revision};}
  async function pull(){const remote=await readRemote();if(!remote)throw new Error('No remote vault exists yet.');CT.storage.captureUndoPoint('sync pull');CT.storage.applyBackup(remote.payload,{source:'sync'});markCommon(remote.payload,remote.etag);CT.events.emit('sync-complete',{direction:'pull',changedAt:remote.payload.changedAt});return {direction:'pull',changedAt:remote.payload.changedAt,revision:remote.payload.syncMeta?.revision||0};}
  async function smartSync(){const remote=await readRemote();if(!remote)return push();const localSnapshot=CT.storage.serializableState();const localHash=await digest(localSnapshot),remoteHash=remote.payload?.syncMeta?.contentHash||await digest(remote.payload),common=localStorage.getItem(C.syncCommonHashKey);const localDiverged=!!common&&localHash!==common,remoteDiverged=!!common&&remoteHash!==common;if(localDiverged&&remoteDiverged&&localHash!==remoteHash){const error=new Error('Sync conflict: both devices changed since the last common revision.');error.code='SYNC_CONFLICT';CT.events.emit('sync-conflict',{localHash,remoteHash,common});throw error;}const localChanged=new Date(localSnapshot.changedAt||0).getTime(),remoteChanged=new Date(remote.payload.changedAt||remote.payload.exportedAt||0).getTime();if(remoteDiverged||remoteChanged>localChanged){CT.storage.captureUndoPoint('sync pull');CT.storage.applyBackup(remote.payload,{source:'sync'});markCommon(remote.payload,remote.etag);CT.events.emit('sync-complete',{direction:'pull',changedAt:remote.payload.changedAt});return {direction:'pull',changedAt:remote.payload.changedAt};}return push();}
  async function exportEncryptedVault(passphrase){const payload=await makePayload(),envelope=await encryptPayload(payload,passphrase),blob=new Blob([JSON.stringify(envelope,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`cert-tracker-${new Date().toISOString().slice(0,10)}.ctvault`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return envelope;}
  function importEncryptedVaultFile(passphrase){return new Promise((resolve,reject)=>{const input=document.createElement('input');input.type='file';input.accept='.ctvault,.json,application/json';input.onchange=event=>{const file=event.target.files?.[0];if(!file)return resolve(false);const reader=new FileReader();reader.onload=async e=>{try{const payload=await decryptPayload(JSON.parse(e.target.result),passphrase);CT.storage.captureUndoPoint('encrypted vault import');CT.storage.applyBackup(payload,{source:'encrypted-file'});resolve(true);}catch(error){reject(error);}};reader.readAsText(file);};input.click();});}
  function scheduleAutoSync(){const config=getConfig();if(!config.autoSync||!session||!config.endpoint)return;clearTimeout(autoTimer);autoTimer=setTimeout(()=>smartSync().catch(error=>{console.warn('[CertTracker] automatic sync skipped',error);CT.events.emit('sync-error',{error});}),5000);}
  CT.events.on('state-saved',scheduleAutoSync);
  CT.sync=Object.freeze({encryptPayload,decryptPayload,digest,getConfig,setConfig,connect,disconnect,isConnected,push,pull,smartSync,exportEncryptedVault,importEncryptedVaultFile,scheduleAutoSync,deviceId,defaultIterations:ITERATIONS});
})(window);
